### ISSUE TITLE
[Warning] when generating total spectrum

### ISSUE THREAD

**Issue by inesboxexa** [AlanRace/SpectralAnalysis#35] opened 2020-08-07 15:16 UTC
Hi Alan,

I get the following warning sometimes:

Warning: Objects of com/alanmrace/JSpectralAnalysis/RegionOfInterest class exist - not clearing java 
> In javaclasspath>local_javapath (line 195)
  In javaclasspath (line 124)
  In javaaddpath (line 71)
  In isValidLicence (line 12)
  In canUseJSpectralAnalysis (line 6)
  In generateFastPreprocessingWorkflow (line 5)
  In PostProcessing/setUpFastMethods (line 145)
  In TotalSpectrum/process (line 26)
  In f_saving_spectra_details (line 57) 
Warning: Objects of com/alanmrace/jimzmlparser/imzml/ImzML class exist - not clearing java 
> In javaclasspath>local_javapath (line 195)
  In javaclasspath (line 124)
  In javaaddpath (line 71)
  In isValidLicence (line 12)
  In canUseJSpectralAnalysis (line 6)
  In generateFastPreprocessingWorkflow (line 5)
  In PostProcessing/setUpFastMethods (line 145)
  In TotalSpectrum/process (line 26)
  In f_saving_spectra_details (line 57) 
Warning: Error occurred while executing the listener callback for event FastMethods defined for class TotalSpectrum:
Error using num2str (line 45)
Input to num2str must be numeric.

Error in f_saving_spectra_details>@(src,canUseFastMethods)disp(['! Using fast Methods? A: ',num2str(canUseFastMethods)]) (line 36)
        addlistener(spectrumGeneration, 'FastMethods', @(src, canUseFastMethods)disp(['! Using fast Methods? A: ' num2str(canUseFastMethods)]));

Error in PostProcessing/setUpFastMethods (line 159)
            notify(this, 'FastMethods', BooleanEventData(canUseFastMethods));

Error in TotalSpectrum/process (line 26)
            [canUseFastMethods, workflow] = this.setUpFastMethods(dataRepresentation);

Error in f_saving_spectra_details (line 57)
        totalSpectrum = spectrumGeneration.process(data); % create total spectrum 
> In PostProcessing/setUpFastMethods (line 159)
  In TotalSpectrum/process (line 26)
  In f_saving_spectra_details (line 57) 
com.alanmrace.JSpectralAnalysis.Spectrum@381cad29

It keep running but I though you might want to be aware of it.

Thanks,
Teresa

**Comment by AlanRace** [comment] 2020-08-11 07:39
I think this is caused by the old licencing system that was in place. I have just removed this in the latest committed version as it is no longer used. Can you confirm whether you are still seeing this warning please?

Thanks,

Alan

**Comment by inesboxexa** [comment] 2020-08-14 16:43
Hey,

I haven’t seen yet again. Might be solved.

Thank you,
Teresa

**Closed** 2020-08-17 07:09 UTC
